export const STARTUP = 'STARTUP';
export const INITIATE_TRACK_LIST = 'INITIATE_TRACK_LIST';
export const SETUP_CONFIGURATION = 'SETUP_CONFIGURATION ';
export const SET_NOW_PLAYING = 'SET_NOW_PLAYING';
